Inheart 243 - Add missing stories, remove Home, add navigation buttons
konradhanus/inheartive.io pull request #43
Opened 2022-10-31 12:18 UTC by pmusialik-intive

2022-10-31 15:30 UTC, KonradKarlinski requested changes

2022-10-31 15:33 UTC, pmusialik-intive commented on libs/ui/molecules/src/lib/Sort/__stories__/Sort.stories.tsx
> +  ));
What do you mean?

2022-10-31 15:34 UTC, pmusialik-intive commented on libs/ui/organisms/src/lib/FilterBar/__stories__/FilterBar.stories.tsx
> +        sortBy={SortKey.Heartcoins}
Not sure if I understand - FilterBar is a component named by us and it contains filter select and sort select

2022-11-02 10:58 UTC, KonradKarlinski approved these changes

2022-11-02 11:00 UTC, merged