INHEART-281: Create full works assets module functionality
konradhanus/inheartive.io pull request #53
Opened 2022-11-16 15:50 UTC by pawelroguski

Add storage functionality
Add database model
Add relations
Create actions for findAll, findOne, create, remove

![Screenshot from 2022-11-16 16-49-41](https://user-images.githubusercontent.com/97616451/202228045-db0418c7-6e4f-4e47-8ee5-b35d5439e772.png)
![Screenshot from 2022-11-16 16-49-29](https://user-images.githubusercontent.com/97616451/202228063-7aa20e93-d1eb-47a1-acf7-e9896a5ac893.png)
![Screenshot from 2022-11-16 16-49-12](https://user-images.githubusercontent.com/97616451/202228104-a46a840e-3f39-434a-b824-7735b6ed9421.png)
![Screenshot from 2022-11-16 16-49-02](https://user-images.githubusercontent.com/97616451/202228121-5be0d926-d70b-4af5-8825-66776fe9fa5c.png)

2022-11-17 11:01 UTC, pmusialik-intive requested changes

2022-11-17 11:01 UTC, pmusialik-intive commented on apps/backend/src/app/assets/assets.service.ts
> +      // @TODO Crate or/and implement Logger functionality
We can add simple logging after my branch merge - I used Logger there

2022-12-13 13:09 UTC, pmusialik-intive approved these changes

2022-12-13 13:43 UTC, BeataKula approved these changes

2022-12-14 15:44 UTC, merged