Inheart 118
konradhanus/inheartive.io pull request #8
Opened 2022-10-11 13:03 UTC by konradhanus

- first e2e test added
- readme updated

2022-10-11 14:24 UTC, zgr92 approved these changes

2022-10-12 07:07 UTC, cierzniak requested changes
- [ ] Update README as suggested in comments

2022-10-12 07:07 UTC, cierzniak commented on README.md
> +### Detox for React Native
Move this section under `## Usage`

2022-10-12 07:07 UTC, cierzniak commented on README.md
> +`brew install applesimutils`
Please use

```
```shell
$ brew tap wix/brew
$ brew tap wix/brew
$ npm i -g jest # install jest globally
\```
```
to show shell commands (I mean to use triple backtick block and command prompt which shows common user should use those commands).

2022-10-12 13:00 UTC, merged